### ISSUE TITLE
`.L` files are being built in `src/main/resources` - causes caching issues

### ISSUE THREAD

**Issue by wgip** [XpressAI/SparkCyclone#512]
Had to remove files like `com/nec/cyclone/cpp/char_int_conv.L` explicitly, SBT did not pick it; this can cause correctness issues & misunderstandings

**Comment by wgip** [comment]
@q10 best if we keep `src/main/resources` fully read-only. I am surprised `.L` files were generated, I understood we copied over to a temp directory somehow.

**Comment by q10** [comment]
Updating `build.sbt` so that the build is performed in the target directory instead of in `src/main/resources`.  In addition, the `make` invocation will also clean out everything except the `.so` artifact for further assurance.

**Comment by q10** [comment]
https://github.com/XpressAI/SparkCyclone/pull/514

**Comment by q10** [comment]
This issue should be fixed now.

**Comment by wgip** [comment]
Still getting this:

`[VE] ERROR: loadlib_handler() dlerror: /tmp/ve-spark-tmp4902612430412994161/_spark_485060495.so: undefined symbol: _ZNK17NullableScalarVecIsE6filterERKSt6vectorImSaImEE
`

Ran `VectorEngine / testQuick` on `w-parquet-cache` branch, after doing `git clean -fXd`; both on a6 and vh001

**Comment by q10** [comment]
I was unable to reproduce this, though this has happened once to me, and was addressed by running `sbt clean`
